const promoMovie = {
  title: `The Grand Budapest Hotel`,
  smallPictureUrl: ``,
  backgroundUrl: `img/bg-the-grand-budapest-hotel.jpg`,
  posterUrl: `img/the-grand-budapest-hotel-poster.jpg`,
  genre: `Drama`,
  releaseDate: new Date(2014, 0),
  description: ``,
  director: ``,
  starring: [],
  runTime: ``,
  reviews: [],
};

const films = [
  {
    title: `Bohemian Rhapsody`,
    smallPictureUrl: `img/bohemian-rhapsody.jpg`,
    backgroundUrl: ``,
    posterUrl: ``,
    genre: ``,
    releaseDate: new Date(),
    description: ``,
    director: ``,
    starring: [],
    runTime: ``,
    reviews: [],
  },

  {
    title: `Aviator`,
    smallPictureUrl: `img/aviator.jpg`,
    backgroundUrl: ``,
    posterUrl: ``,
    genre: ``,
    releaseDate: new Date(),
    description: ``,
    director: ``,
    starring: [],
    runTime: ``,
    reviews: [],
  },

  {
    title: `Revenant`,
    smallPictureUrl: `img/revenant.jpg`,
    backgroundUrl: ``,
    posterUrl: ``,
    genre: ``,
    releaseDate: new Date(),
    description: ``,
    director: ``,
    starring: [],
    runTime: ``,
    reviews: [],
  },

  {
    title: `Johnny English`,
    smallPictureUrl: `img/johnny-english.jpg`,
    backgroundUrl: ``,
    posterUrl: ``,
    genre: ``,
    releaseDate: new Date(),
    description: ``,
    director: ``,
    starring: [],
    runTime: ``,
    reviews: [],
  },

  {
    title: `Shutter Island`,
    smallPictureUrl: `img/shutter-island.jpg`,
    backgroundUrl: ``,
    posterUrl: ``,
    genre: ``,
    releaseDate: new Date(),
    description: ``,
    director: ``,
    starring: [],
    runTime: ``,
    reviews: [],
  },

  {
    title: `Pulp Fiction`,
    smallPictureUrl: `img/pulp-fiction.jpg`,
    backgroundUrl: ``,
    posterUrl: ``,
    genre: ``,
    releaseDate: new Date(),
    description: ``,
    director: ``,
    starring: [],
    runTime: ``,
    reviews: [],
  },

  {
    title: `Seven Years in Tibet`,
    smallPictureUrl: `img/seven-years-in-tibet.jpg`,
    backgroundUrl: ``,
    posterUrl: ``,
    genre: ``,
    releaseDate: new Date(),
    description: ``,
    director: ``,
    starring: [],
    runTime: ``,
    reviews: [],
  },

  {
    title: `Snatch`,
    smallPictureUrl: `img/snatch.jpg`,
    backgroundUrl: ``,
    posterUrl: ``,
    genre: ``,
    releaseDate: new Date(),
    description: ``,
    director: ``,
    starring: [],
    runTime: ``,
    reviews: [],
  },
];

const genreNames = [
  `All genres`,
  `Comedies`,
  `Crime`,
  `Documentary`,
  `Dramas`,
  `Horror`,
  `Kids & Family`,
  `Romance`,
  `Sci-Fi`,
  `Thrillers`,
];


export {
  genreNames,
  promoMovie,
  films,
};
