const NUMBER_OF_CARDS_IN_CATALOG_AT_STARTUP = 8;
const NUMBER_OF_CARDS_TO_INCREMENT = 8;
const MAX_FILTER_ELEMENTS_COUNT = 10;
const NUMBER_OF_SIMILAR_FILMS = 4;
const VISIBLE_PARTICIPANTS_COUNT = 4;
const DELAY_PLAYBACK_PREVIEW = 1000;
const MIN_REVIEW_TEXT_LEMGTH = 50;
const MAX_REVIEW_TEXT_LEMGTH = 400;
const RATING_RANGE = 5;

const PageType = {
  MAIN: `main`,
  MOVIE_DETAILS: `movie-details`,
  PLAYER: `player`,
  ERROR: `error`,
  SIGN_IN: `sign-in`,
  ADD_REVIEW: `add-review`,
};


export {
  DELAY_PLAYBACK_PREVIEW,
  MAX_FILTER_ELEMENTS_COUNT,
  MAX_REVIEW_TEXT_LEMGTH,
  MIN_REVIEW_TEXT_LEMGTH,
  NUMBER_OF_CARDS_IN_CATALOG_AT_STARTUP,
  NUMBER_OF_CARDS_TO_INCREMENT,
  NUMBER_OF_SIMILAR_FILMS,
  RATING_RANGE,
  VISIBLE_PARTICIPANTS_COUNT,
  PageType,
};
